[project]
name = "calculator"
version = "1.2.0"
description = "Add your description here"
readme = "../README.md"
authors = [
    { name = "dyy", email = "yuyangd473@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
python = "python:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
[tool.uv]
package = false

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
    "pytest>=8.3.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
